on:
  - pull_request
  - push
  - workflow_dispatch

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - "8.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xdebug
          coverage: pcov

      - name: Install composer dependencies
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit
        run: vendor/bin/phpunit
